export const GRAB_INVOICES_SUCCESFUL = 'GRAB_INVOICES_SUCCESFUL';
export const GRAB_INVOICES_PENDING = 'GRAB_INVOICES_PENDING';
export const GRAB_INVOICES_FAILURE = 'GRAB_INVOICES_FAILURE';
export const UPDATE_INVOICE_PENDING = 'UPDATE_INVOICE_PENDING';
export const UPDATE_INVOICE_SUCCESS = 'UPDATE_INVOICE_SUCCESS';
export const UPDATE_INVOICE_FAILED = 'UPDATE_INVOICE_FAILED';